### ISSUE TITLE
Gamma argument with strata

### ISSUE THREAD

**Issue by DanChaltiel** [keaven/gsDesign#10]
Dear Keaven,

When using `gsSurv` with 2 strata, it seems that the `gamma` argument is not used, as using 1 or 9999 ended in the same result. I admit I am a bit confused about why.

However, it seems that you cannot leave it as default either, as it has to be a matrix of the same dimension as `lambdaC`.

Here is a reproducible example:

```
gsDesign::gsSurv(k=2, test.type=4, timing=c(0.5,1), 
                 lambdaC=matrix(c(s1=-log(0.51)/3, s2=-log(0.49)/3), ncol=2), 
                 # gamma=1, 
                 gamma=matrix(1, ncol=2), 
                 #gamma=matrix(9999, ncol=2), 
                 ratio=c(s1=0.315, s2=0.656),
                 hr=0.6, T=6, minfup=3, 
                 sided =2, alpha=0.05, beta=0.2)
```

Am I doing it wrong or is this an irregular behavior?

**PS:** it seems that this facet of your package uses a deprecated feature, as I get the warning "Recycling array of length 1 in array-vector arithmetic is deprecated. Use c() or as.vector() instead." at more than 20 points with the above code. It seems that we can [ignore this warning](https://stackoverflow.com/a/55884362/3888000) though.

**Comment by nanxstats** [comment]
Seems relevant to our current updates - Keaven will take a look.

**Comment by keaven** [comment]
Sorry for the long delay in responding. gamma is used for relative enrollment rates. Thus,
gamma= matrix(1:2,ncol=2) will give a different answer than gamma=matrix(2:1,ncol = 2).
On the other hand the following 2 will produce the same result.
gamma <- matrix(c(1,2), ncol=2)
gamma <- matrix(c(2,4), ncol=2)
We are still working on updating stratified sample size in another issue.
