### ISSUE TITLE
`as_gt` and `as_rtf` methods for `gsBoundSummary()` objects

### ISSUE THREAD

**Issue by nanxstats** [keaven/gsDesign#100]
Similar to https://github.com/Merck/gsDesign2/issues/130 and https://github.com/Merck/gsDesign2/issues/108.

`gsBoundSummary()` offers summary table outputs as data frames. We received feedback that it would be ideal to natively support important table backend types to facilitate standardized reporting. Notably, RTF outputs using r2rtf, and gt outputs.

Currently (August 2023):

- The `as_gt()` [method](https://keaven.github.io/gsDesign/reference/as_gt.html) is implemented for `gsBinomialExact()` objects only.
- Vanilla `gt()` tables are used in the [gsSurv basic examples vignette](https://keaven.github.io/gsDesign/articles/gsSurvBasicExamples.html), [Poisson mixture model vignette](https://keaven.github.io/gsDesign/articles/PoissonMixtureModel.html), and [vaccine efficacy trial design vignette](https://keaven.github.io/gsDesign/articles/VaccineEfficacy.html) ad-hoc.

@LittleBeannie is looking for potential contributors on this.

**Comment by LittleBeannie** [comment]
Hi @nanxstats, could you please give @fukuhiro2023 the write access? He will work on the `as_rtf()` development of `gsBoundSummary()` with @wangben718.

**Comment by nanxstats** [comment]
> Hi @nanxstats, could you please give @fukuhiro2023 the write access? He will work on the `as_rtf()` development of `gsBoundSummary()` with @wangben718.

Keaven can help with access.

**Comment by nanxstats** [comment]
Ben has finished development for the `as_rtf()` method for `gsBinomialExact()` in #102. Currently working on adding `as_gt()` and `as_rtf()` methods for `gsBoundSummary()` outputs. Will follow up on those in #107.
