### ISSUE TITLE
Feature request: Futility analysis only

### ISSUE THREAD

**Issue by DanChaltiel** [keaven/gsDesign#106]
Hi,

As for now, it is possible to perform the efficacy analysis only using `test.type=1`.
However, I sometimes need to perform the futility analysis only.
This is something you can do with East, for example.

To illustrate, here is the East output for efficacy, futility, and both: [east.zip](https://github.com/keaven/gsDesign/files/12618386/east.zip).

Would you consider this feature?

**Comment by nanxstats** [comment]
This is natively supported by [gsDesign2](https://merck.github.io/gsDesign2/).

In gsDesign, you can work around this by setting a piecewise spending function with **very** small late incremental spending.

**Comment by keaven** [comment]
Link above has a good explanation using gsDesign2. Let us know if you still need help with the gsDesign example...
