### ISSUE TITLE
Independent testing of `gsSurvCalendar()`

### ISSUE THREAD

**Issue by LittleBeannie** [keaven/gsDesign#137]
MJ, please write your test plan here.

**Comment by myeongjong** [comment]
1. Introduction
gsDesign allows substantial flexibility for clinical study interim analyses. In particular, [`gsSurv()`](https://github.com/keaven/gsDesign/blob/master/R/gsSurv.R) plays a crucial role in the derivation of a group sequential design (Jennison and Turnbull, 1999) for a time-to-event clinical trial that employs information-based timing and spending. [`gsSurvCalendar()`](https://github.com/keaven/gsDesign/blob/master/R/gsSurvCalendar.R) is akin to `gsSurv()`, which derives group sequential designs for time-to-event endpoint studies with calendar-based timing. Note that participants enrollment occurs in calendar time while interim summary statistics depend on the amount of information available (Land and Demets, 1989). Accordingly, conducting a comparative analysis between `gsSurv()` and `gsSurvCalendar()` would be a meaningful step for testing `gsSurvCalendar()`. The tester will compare outputs of the two functions to verify that `gsSurvCalendar()` provides correct outputs, and validate its user-friendliness.

1. Scope
This test plan aims to verify the functionality and features of `gsSurvCalendar()` by comparing its outputs with `gsSurv()`'s ones for corresponding inputs and validate user friendliness of `gsSurvCalendar()` to make sure if `gsSurv()` users can easily get familiar with `gsSurvCalendar()`.

1. Test Strategy
The tester will implement a two-way testing approach: 

1. Test Schedule (tentative)

1. Deliverables

1. Reference
- Lan, K. G., & DeMets, D. L. (1989). Group sequential procedures: calendar versus information time. Statistics in Medicine, 8(10), 1191-1198.
- Jennison, C., & Turnbull, B. W. (1999). Group sequential methods with applications to clinical trials. CRC Press.
