### ISSUE TITLE
Release gsDesign 3.2.0

### ISSUE THREAD

**Issue by elong0527** [keaven/gsDesign#18]
- [x] ensure github pkgdown and cove coverage works (Yilong) 
- [x] remove `plyr` dependency
- [x] change `xtable` dependency to suggest
- [x] update code coverage report. 
- [x] remove `inst/unitTests` and `revdep` folder
- [x] update .Buildignore file to reduce CRAN submission file
- [x] go through information in https://r-pkgs.org/release.html
        + also refer checklist in: https://github.com/tidyverse/tidyverse/issues/178 

Before Submission:
-[] update `cran-comments.md`

**Comment by nanxstats** [comment]
We should close this as 3.2.0 is now on CRAN.
