### ISSUE TITLE
Potential bug in gsDesign::nSurvival and vectorized inputs 

### ISSUE THREAD

**Issue by elong0527** [keaven/gsDesign#2]
On behalf of Anders. 

Your nSurvival function accept and runs without hesitation on vector inputs. And the printing method works as well (with minor formatting issues). However, the results do not seem to be correct when doing so (see below). I am aware that in the documentation only nEvents is explicitly stated to support vectors as inputs. So I assumed nSurvival did as well. But after I have been looking at the source, I now think vector inputs are not supported nor intended for nSurvival, correct?  

If so, perhaps you should consider either checking the inputs for being scalars in nSurvival and throw an error if not. Alternatively (and better), consider adding support for vector inputs. I would not expect most R users would notice this discrepancy.

Let me know if I have been unclear anywhere. 

To elaborate a bit, I think issue arises by the way you pass to gsDesign::pe through sapply. However, as you can see below, I a bit baffled why it appears to work with the default Ts and Tr parameters.

```
library(“gsDesign”)

# This does not work as (I) expected
dfX <- data.frame(unclass(nSurvival(
  lambda1 = 1,
  lambda2 = 2, 
  Ts = 2, 
  Tr = 2)))

dfY <- data.frame(unclass(nSurvival(
  lambda1 = 1,
  lambda2 = 3, 
  Ts = 2, 
  Tr = 2)))

dfZ <- data.frame(unclass(nSurvival(
  lambda1 = 1,
  lambda2 = c(2, 3), 
  Ts = 2, 
  Tr = 2)))

dfX
dfY
dfZ

# This seems to work as expected
df1 <- data.frame(unclass(nSurvival(lambda1 = 1, lambda2 = 2)))
df2 <- data.frame(unclass(nSurvival(lambda1 = 1, lambda2 = 3)))
df3 <- data.frame(unclass(nSurvival(lambda1 = 1, lambda2 = 4)))
df4 <- data.frame(unclass(nSurvival(lambda1 = 1, lambda2 = c(2, 3, 4))))

df1
df2
df3
df4
```

**Comment by nanxstats** [comment]
@elong0527 Is this issue fixed? Can this issue be closed? If not, do we need more clarification?

**Comment by nanxstats** [comment]
We recommend `gsDesign::nSurv()` and `gsDesign::gsSurv()`.
