### ISSUE TITLE
Create a conda package

### ISSUE THREAD

**Issue by matthewwardrop** [keaven/gsDesign#24]
Hi @keaven ,

I am interested in consuming gsDesign as a dependency of a conda package we ship at work, and was wondering if you have any objections to this package being included into [Conda Forge](https://conda-forge.org/). I am happy to put together the required metadata and build scripts, and can add you as a maintainer if you are willing.

Best,
M

**Comment by nanxstats** [comment]
Looks like this is already resolved: https://anaconda.org/conda-forge/r-gsdesign so I'm closing this.

Thanks for the contribution to make gsDesign available for a broader community!
