### ISSUE TITLE
Change default weight character to alpha in hGraph

### ISSUE THREAD

**Issue by keaven** [keaven/gsDesign#45]
hGraph(wchar  = '\u03b1') works both on Linux and Window; change to this default. Documentation and vignette need updating to demonstrate this vs the "w" character used for weights in literature.

**Comment by allenzhuaz** [comment]
This issue is fixed in [056390f](https://github.com/allenzhuaz/gMCPmini/commit/056390f) and [1615732](https://github.com/allenzhuaz/gMCPmini/pull/27/commits/16157323719beacde50d997d8818d91fc884448f), so it can be closed

**Comment by nanxstats** [comment]
Let's close this and create a new ticket on start deprecating `gsDesign::hGraph()`.
