### ISSUE TITLE
gsDesign boundary error for one-sided and two-sided WT test

### ISSUE THREAD

**Issue by snailymj** [keaven/gsDesign#60]
I found an error: the following two commands give the same Z-value boundary. They are special cases for Pocock test, and the second one (two-sided) seems wrong.
gsDesign::gsDesign(timing=c(0.5,1), alpha=0.05,   sfu="WT", sfupar=0.5, k=2,test.type=**1**)
gsDesign::gsDesign(timing=c(0.5,1), alpha=0.05,   sfu="WT", sfupar=0.5, k=2,test.type=**2**)

**Comment by keaven** [comment]
If you save these and look at the difference between n.I, the upper bounds, and upper boundary crossing probabilities, you will see that results are SLIGHTLY different.

x1Sided <- gsDesign::gsDesign(timing=c(0.5,1), alpha=0.05, sfu="WT", sfupar=0.5, k=2,test.type=1)
x2Sided <- gsDesign::gsDesign(timing=c(0.5,1), alpha=0.05, sfu="WT", sfupar=0.5, k=2,test.type=2)
x1Sided$n.I - x2Sided$n.I
x1Sided$upper$prob - x2Sided$upper$prob
