### ISSUE TITLE
Add comment of `eEvents1` and `eEvents`

### ISSUE THREAD

**Issue by LittleBeannie** [keaven/gsDesign#91]
related to an issue in gsDesign2: https://github.com/Merck/gsDesign2/issues/250.

**Comment by nanxstats** [comment]
Hey @LittleBeannie can this issue be closed or do you still want to add comments to `eEvents()` besides `eEvents1()`?

**Comment by LittleBeannie** [comment]
> Hey @LittleBeannie can this issue be closed or do you still want to add comments to `eEvents()` besides `eEvents1()`?

Since the PR is merged, let's close this issue.
